version: '3.5'
services:
  service-outing:
    image: migsking/dms-sms-service-outing:${VERSION}
    container_name: service-outing
    networks:
      - dms-sms-local
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - CONSUL_ADDR=${CONSUL_ADDRESS}
      - JAEGER_ADDR=${JAEGER_ADDRESS}

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge
