apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: service-outing
  name: service-outing
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-outing
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/dms-sms-local: "true"
        io.kompose.service: service-outing
    spec:
      containers:
        - env:
            - name: CONSUL_ADDR
              value: "$CONSUL_ADDR"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
            - name: JAEGER_ADDR
              value: "$JAEGER_ADDR"
          image: 'jinhong0719/dms-sms-service-outing:$VERSION'
          name: service-outing
          resources: {}
      restartPolicy: Always
status: {}
