name: docker-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  DOCKER_BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t migsking/dsm-sms-service-outing .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: migsking/chateaubriand
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
